11/11 update
First try on building the architecture. But got the error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_32904/1466654159.py in <module>
     15
     16
---> 17         y_raw = model(x1, x2)
     18         y_hat = softmax(y_raw)
     19

c:\Users\light\Documents\RoadToCreation\python\NLP_env\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~\AppData\Local\Temp/ipykernel_32904/1991182659.py in forward(self, sequence_1, sequence_2)
     21         token_1 = tokenizer(sequence_1)
     22         token_2 = tokenizer(sequence_2)
---> 23         output_1 = self.l1(input_ids=torch.tensor(token_1["input_ids"]).unsqueeze(0), attention_mask=torch.tensor(token_1["attention_mask"]).unsqueeze(0))
     24         output_2 = self.l1(input_ids=torch.tensor(token_2["input_ids"]).unsqueeze(0), attention_mask=torch.tensor(token_2["attention_mask"]).unsqueeze(0))
     25         # RobertaModel(RobertaConfig())

c:\Users\light\Documents\RoadToCreation\python\NLP_env\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

c:\Users\light\Documents\RoadToCreation\python\NLP_env\lib\site-packages\transformers\models\roberta\modeling_roberta.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
    841         head_mask = self.get_head_mask(head_mask, self.config.num_hidden_layers)
    842
--> 843         embedding_output = self.embeddings(
    844             input_ids=input_ids,
    845             position_ids=position_ids,

c:\Users\light\Documents\RoadToCreation\python\NLP_env\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

c:\Users\light\Documents\RoadToCreation\python\NLP_env\lib\site-packages\transformers\models\roberta\modeling_roberta.py in forward(self, input_ids, token_type_ids, position_ids, inputs_embeds, past_key_values_length)
    129
    130         if inputs_embeds is None:
--> 131             inputs_embeds = self.word_embeddings(input_ids)
    132         token_type_embeddings = self.token_type_embeddings(token_type_ids)
    133

c:\Users\light\Documents\RoadToCreation\python\NLP_env\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

c:\Users\light\Documents\RoadToCreation\python\NLP_env\lib\site-packages\torch\nn\modules\sparse.py in forward(self, input)
    156
    157     def forward(self, input: Tensor) -> Tensor:
--> 158         return F.embedding(
    159             input, self.weight, self.padding_idx, self.max_norm,
    160             self.norm_type, self.scale_grad_by_freq, self.sparse)

c:\Users\light\Documents\RoadToCreation\python\NLP_env\lib\site-packages\torch\nn\functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   2042         # remove once script supports set_grad_enabled
   2043         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2044     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   2045
   2046

IndexError: index out of range in self